const sp_weapon_data = {
    "10000": {
        "id": 10000,
        "icon": "10000",
        "eq_reload": [],
        "rarity": 4,
        "tech": 0,
        "limit": 10117,
        "type": 1,
        "jp_name": "勇ましい夢を見る枕",
        "en_name": "Huggy Pillow of Bravery",
        "cn_name": "勇敢的美梦之枕",
        "tw_name": "勇敢的美夢之枕*"
    },
    "10020": {
        "id": 10020,
        "icon": "10020",
        "eq_reload": [
            13,
            14,
            14,
            15,
            15,
            16,
            16,
            17,
            18,
            19,
            20
        ],
        "rarity": 4,
        "tech": 0,
        "limit": 20212,
        "type": 2,
        "jp_name": "波打つ優雅な午後",
        "en_name": "Afternoon of Surging Elegance",
        "cn_name": "波涛与优雅的午后",
        "tw_name": "波濤與優雅的午後*"
    },
    "10040": {
        "id": 10040,
        "icon": "10040",
        "eq_reload": [],
        "rarity": 4,
        "tech": 0,
        "limit": 40303,
        "type": 4,
        "jp_name": "幸運艦のシュトラーフェ",
        "en_name": "Lucky Ship's \"Punishers\"",
        "cn_name": "幸运舰的“惩罚”",
        "tw_name": "幸運艦的“懲罰”*"
    },
    "10060": {
        "id": 10060,
        "icon": "10060",
        "eq_reload": [
            10,
            11,
            11,
            12,
            12,
            13,
            13,
            14,
            14,
            15,
            15
        ],
        "rarity": 4,
        "tech": 0,
        "limit": 10504,
        "type": 6,
        "jp_name": "もう泣かないで",
        "en_name": "No More Tears",
        "cn_name": "不再哭泣",
        "tw_name": "不再哭泣*"
    },
    "10080": {
        "id": 10080,
        "icon": "10080",
        "eq_reload": [
            7,
            8,
            8,
            9,
            9,
            10,
            10,
            11,
            11,
            12,
            12
        ],
        "rarity": 4,
        "tech": 0,
        "limit": 30803,
        "type": 8,
        "jp_name": "聴音バランス装置",
        "en_name": "Hydrophone Calibration Device",
        "cn_name": "探测平衡装置",
        "tw_name": "探測平衡裝置*"
    },
    "1010100": {
        "id": 1010100,
        "icon": "1010100",
        "eq_reload": [],
        "rarity": 2,
        "tech": 1,
        "limit": 0,
        "type": 1,
        "jp_name": "饅頭ダブルソード",
        "en_name": "Dual Swords",
        "cn_name": "双剑",
        "tw_name": "雙劍*"
    },
    "1010120": {
        "id": 1010120,
        "icon": "1010100",
        "eq_reload": [],
        "rarity": 3,
        "tech": 2,
        "limit": 0,
        "type": 1,
        "jp_name": "饅頭ダブルソード",
        "en_name": "Dual Swords",
        "cn_name": "双剑",
        "tw_name": "雙劍*"
    },
    "1010200": {
        "id": 1010200,
        "icon": "1010200",
        "eq_reload": [],
        "rarity": 2,
        "tech": 1,
        "limit": 0,
        "type": 1,
        "jp_name": "饅頭ハンマー",
        "en_name": "Hammer",
        "cn_name": "单手锤",
        "tw_name": "單手錘*"
    },
    "1010220": {
        "id": 1010220,
        "icon": "1010200",
        "eq_reload": [],
        "rarity": 3,
        "tech": 2,
        "limit": 0,
        "type": 1,
        "jp_name": "饅頭ハンマー",
        "en_name": "Hammer",
        "cn_name": "单手锤",
        "tw_name": "單手錘*"
    },
    "1020100": {
        "id": 1020100,
        "icon": "1020100",
        "eq_reload": [
            4,
            3,
            3,
            5,
            5,
            6,
            6,
            7,
            7,
            8,
            8
        ],
        "rarity": 2,
        "tech": 1,
        "limit": 0,
        "type": 2,
        "jp_name": "饅頭ソード",
        "en_name": "Sword",
        "cn_name": "铁剑",
        "tw_name": "鐵劍*"
    },
    "1020120": {
        "id": 1020120,
        "icon": "1020100",
        "eq_reload": [
            8,
            3,
            3,
            9,
            9,
            10,
            10,
            11,
            11,
            12,
            12
        ],
        "rarity": 3,
        "tech": 2,
        "limit": 0,
        "type": 2,
        "jp_name": "饅頭ソード",
        "en_name": "Sword",
        "cn_name": "铁剑",
        "tw_name": "鐵劍*"
    },
    "1030100": {
        "id": 1030100,
        "icon": "1030100",
        "eq_reload": [],
        "rarity": 2,
        "tech": 1,
        "limit": 0,
        "type": 3,
        "jp_name": "饅頭クロスボウ",
        "en_name": "Crossbow",
        "cn_name": "手弩",
        "tw_name": "手弩*"
    },
    "1030120": {
        "id": 1030120,
        "icon": "1030100",
        "eq_reload": [],
        "rarity": 3,
        "tech": 2,
        "limit": 0,
        "type": 3,
        "jp_name": "饅頭クロスボウ",
        "en_name": "Crossbow",
        "cn_name": "手弩",
        "tw_name": "手弩*"
    },
    "1040100": {
        "id": 1040100,
        "icon": "1040100",
        "eq_reload": [],
        "rarity": 2,
        "tech": 1,
        "limit": 0,
        "type": 4,
        "jp_name": "饅頭バスターソード",
        "en_name": "Greatsword",
        "cn_name": "大剑",
        "tw_name": "大劍*"
    },
    "1040120": {
        "id": 1040120,
        "icon": "1040100",
        "eq_reload": [],
        "rarity": 3,
        "tech": 2,
        "limit": 0,
        "type": 4,
        "jp_name": "饅頭バスターソード",
        "en_name": "Greatsword",
        "cn_name": "大剑",
        "tw_name": "大劍*"
    },
    "1050100": {
        "id": 1050100,
        "icon": "1050100",
        "eq_reload": [],
        "rarity": 2,
        "tech": 1,
        "limit": 0,
        "type": 5,
        "jp_name": "饅頭ランス",
        "en_name": "Lance",
        "cn_name": "骑枪",
        "tw_name": "騎槍*"
    },
    "1050120": {
        "id": 1050120,
        "icon": "1050100",
        "eq_reload": [],
        "rarity": 3,
        "tech": 2,
        "limit": 0,
        "type": 5,
        "jp_name": "饅頭ランス",
        "en_name": "Lance",
        "cn_name": "骑枪",
        "tw_name": "騎槍*"
    },
    "1060100": {
        "id": 1060100,
        "icon": "1060100",
        "eq_reload": [],
        "rarity": 2,
        "tech": 1,
        "limit": 0,
        "type": 6,
        "jp_name": "饅頭オフィサーソード",
        "en_name": "Officer's Sword",
        "cn_name": "指挥刀",
        "tw_name": "指揮刀*"
    },
    "1060120": {
        "id": 1060120,
        "icon": "1060100",
        "eq_reload": [],
        "rarity": 3,
        "tech": 2,
        "limit": 0,
        "type": 6,
        "jp_name": "饅頭オフィサーソード",
        "en_name": "Officer's Sword",
        "cn_name": "指挥刀",
        "tw_name": "指揮刀*"
    },
    "1060200": {
        "id": 1060200,
        "icon": "1060200",
        "eq_reload": [],
        "rarity": 2,
        "tech": 1,
        "limit": 0,
        "type": 6,
        "jp_name": "饅頭ボウガン",
        "en_name": "Bowgun",
        "cn_name": "轻弩",
        "tw_name": "輕弩*"
    },
    "1060220": {
        "id": 1060220,
        "icon": "1060200",
        "eq_reload": [],
        "rarity": 3,
        "tech": 2,
        "limit": 0,
        "type": 6,
        "jp_name": "饅頭ボウガン",
        "en_name": "Bowgun",
        "cn_name": "轻弩",
        "tw_name": "輕弩*"
    },
    "1070100": {
        "id": 1070100,
        "icon": "1070100",
        "eq_reload": [],
        "rarity": 2,
        "tech": 1,
        "limit": 0,
        "type": 7,
        "jp_name": "饅頭ハンターボウ",
        "en_name": "Hunting Bow",
        "cn_name": "猎弓",
        "tw_name": "獵弓*"
    },
    "1070120": {
        "id": 1070120,
        "icon": "1070100",
        "eq_reload": [],
        "rarity": 3,
        "tech": 2,
        "limit": 0,
        "type": 7,
        "jp_name": "饅頭ハンターボウ",
        "en_name": "Hunting Bow",
        "cn_name": "猎弓",
        "tw_name": "獵弓*"
    },
    "1070200": {
        "id": 1070200,
        "icon": "1070200",
        "eq_reload": [],
        "rarity": 2,
        "tech": 1,
        "limit": 0,
        "type": 7,
        "jp_name": "饅頭セプター",
        "en_name": "Scepter",
        "cn_name": "权杖",
        "tw_name": "權杖*"
    },
    "1070220": {
        "id": 1070220,
        "icon": "1070200",
        "eq_reload": [],
        "rarity": 3,
        "tech": 2,
        "limit": 0,
        "type": 7,
        "jp_name": "饅頭セプター",
        "en_name": "Scepter",
        "cn_name": "权杖",
        "tw_name": "權杖*"
    },
    "1080100": {
        "id": 1080100,
        "icon": "1080100",
        "eq_reload": [],
        "rarity": 2,
        "tech": 1,
        "limit": 0,
        "type": 8,
        "jp_name": "饅頭ダガー",
        "en_name": "Dagger",
        "cn_name": "短剑",
        "tw_name": "短劍*"
    },
    "1080120": {
        "id": 1080120,
        "icon": "1080100",
        "eq_reload": [],
        "rarity": 3,
        "tech": 2,
        "limit": 0,
        "type": 8,
        "jp_name": "饅頭ダガー",
        "en_name": "Dagger",
        "cn_name": "短剑",
        "tw_name": "短劍*"
    },
    "1080200": {
        "id": 1080200,
        "icon": "1080200",
        "eq_reload": [],
        "rarity": 2,
        "tech": 1,
        "limit": 0,
        "type": 8,
        "jp_name": "饅頭クナイ",
        "en_name": "Kunai",
        "cn_name": "苦无",
        "tw_name": "苦無*"
    },
    "1080220": {
        "id": 1080220,
        "icon": "1080200",
        "eq_reload": [],
        "rarity": 3,
        "tech": 2,
        "limit": 0,
        "type": 8,
        "jp_name": "饅頭クナイ",
        "en_name": "Kunai",
        "cn_name": "苦无",
        "tw_name": "苦無*"
    }
};
